### ISSUE TITLE
[Primer Web] Link to Label documentation is broken

### ISSUE THREAD

**Issue by josepmartins** [primer/figma#12]
The link to the react documentation should be https://primer.style/react/Label instead 👍 

<img width="652" alt="Screenshot 2022-08-18 at 11 06 57" src="https://user-images.githubusercontent.com/912236/185356959-1ef981bd-4a5d-4523-8461-17db56fe6004.png">

**Comment by lukasoppermann** [comment]
Fixed, thank you for the find.
