### ISSUE TITLE
Workflow improvements for adding components

### ISSUE THREAD

**Issue by lukasoppermann** [primer/figma#14]
While working on my first figma related ticket (adapting the segmented control) I came across a few things that would help me and may have helped the contributor to provide a component that is even more polished.

## Contribution checklist
This is a quick and easily scannable version of the contribution guidelines.
- naming
- layers
- docs
- states
- ... 
All with links to get the details about it.

## Contribution guidelines
- A more detailed version of the checklist based on [authoring components](https://github.com/primer/figma/blob/main/docs/authoring-components.md)
- suggest people create branches directly (? is that desired?)
- what is expected as the minimum for a figma PR
- what is included in the perfect PR
- all the naming, etc. guidelines but more detailed (e.g. with ALL commonly used properties)

## Small improvements
- [authoring components](https://github.com/primer/figma/blob/main/docs/authoring-components.md) or the new **contribution guidelines** should be linked on the readme of this repo and throughout the docs more often
- It should be better described when to use a toggle or a dropdown in figma components
- Some guidance around when to add a disabled state
- some guidance around what colors to use and for what the tokens are

**Comment by ashygee** [comment]
Hey @lukasoppermann I think we can separate this into other issues within [primer/design](https://github.com/primer/design) and here. Especially now that we have updated the [contribution guidelines](https://github.com/primer/figma/blob/main/docs/contribution.md), I feel this can be closed out and the following can be addressed in Interface Guidelines:

> - It should be better described when to use a toggle or a dropdown in figma components
> - Some guidance around when to add a disabled state
> - some guidance around what colors to use and for what the tokens are

If you agree let's move forward with closing this issue. :)

The only suggestion I might have would be to move the contribution guidelines out of the `/docs` directory and into the root as `CONTRIBUTION.md` since that's a more common file structure.

**Comment by lukasoppermann** [comment]
Yeah, @mperrotti asked me to note down my ideas, as I was coming to the project all new with a fresh (read: no clue 😁 ) perspective.

> The only suggestion I might have would be to move the [contribution guidelines](https://github.com/primer/figma/blob/main/docs/contribution.md) out of the /docs directory and into the root as CONTRIBUTION.md since that's a more common file structure.

Yes, great idea. 👍 

One thing I feel is still missing is:

> 
> This is a quick and easily scannable version of the contribution guidelines.
> 
> naming
> layers
> docs
> states
> ...
> All with links to get the details about it.

It would be great to add a small checklist to `CONTRIBUTION.md` and link the items to the detailed version in [authoring-components.md](https://github.com/primer/figma/blob/main/docs/authoring-components.md).

Just so people who basically now all of it don't have to go through the long document. What do you think?
