### ISSUE TITLE
Checkbox: Indeterminate state

### ISSUE THREAD

**Issue by stvehayes** [primer/figma#24]
**Does the component exist in any of the code implementations?**
Yes. It's in prod, as well as [Primer React](https://primer.style/react/Checkbox).

**Describe the use case**
This is for the indeterminate state, typically used in a checkbox list. In production, we use a gray outline version and in Figma we have it styled the same as the checked state. It appears that the gray version is what we're using in the product as well as in Primer React.

**Describe alternatives you've considered**
N/A

**Additional context**
### Production
![CleanShot 2022-10-27 at 12 38 37](https://user-images.githubusercontent.com/13389614/198348909-34cd9b65-9463-45de-9580-41725f874ee3.png)

### Figma
![CleanShot 2022-10-27 at 12 39 40](https://user-images.githubusercontent.com/13389614/198349095-34eb8959-4038-4c06-9ad4-b01a856efe69.png)

**Have you built this in figma already or would you like to?**
See above. This is the `CheckboxInput` component with `check type: indeterminate`.

**Comment by lukasoppermann** [comment]
Hey @stvehayes thanks for raising this issue.

It turns out we use the native checkbox component, which may be grey in some browsers and blue in others (Safari should be blue).

So this one is correct. However we can look at what is more typical and potentially add the grey one as well (or replace it).

**Comment by stvehayes** [comment]
Sounds good! Thanks for the update – as long as it's correct that was my main concern 😄
