### ISSUE TITLE
Flash component flexibility

### ISSUE THREAD

**Issue by nuthinking** [primer/figma#3]
<img width="841" alt="Flash" src="https://user-images.githubusercontent.com/163635/106788459-41f6a780-6651-11eb-81b4-72f55185a49f.png">

- Without the CTA it doesn't expand full width
- When the text is long it doesn't expand vertically
- There is not option to make the Flash not dismissable (no close button) and preserve the left icon.

**Comment by ashygee** [comment]
Thanks @nuthinking, this component looks like it needs to be refactored and I think it can utilize a new way of thinking with auto layout. I'm adding this to my project board and update to this issue as improvements are made.
