### ISSUE TITLE
TextInput is missing thicker border

### ISSUE THREAD

**Issue by nuthinking** [primer/figma#4]
Annoyingly looks like that because it is a component I can't add further strokes 🤷‍♂️

<img width="1034" alt="Screenshot 2021-02-04 at 15 16 45" src="https://user-images.githubusercontent.com/163635/106905073-314f3b80-66fc-11eb-9e3c-ee24ccbc64ca.png">

**Comment by ashygee** [comment]
This has been fixed and the change is present moving forward from this [version](https://www.figma.com/file/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?version-id=667588366&node-id=142%3A596&viewport=-1319%2C-549%2C0.48489582538604736) of Primer Web.

![image](https://user-images.githubusercontent.com/10384315/107249042-cba6cc00-69e7-11eb-8db3-8110196a37c0.png)


- Focus border added to input focus state. When Clip content is unchecked, the spread of a shadow effect no longer shows. The input focus now uses state/focus/shadow to enable the blue focus shadow. This closes [#4](https://github.com/primer/figma/issues/4)
