### ISSUE TITLE
Breadcrumb inconsistency

### ISSUE THREAD

**Issue by ichelsea** [primer/figma#7]
The current page for [breadcrumbs in primer's docs](https://primer.style/css/components/breadcrumb) has a normal font weight and the dividers are using color: #e1e4e8 -breadcrumb-item: 
![""](https://user-images.githubusercontent.com/40274682/110013459-7f913380-7cd6-11eb-8cf8-f9c7234dfc49.png)

In Figma the font is using our bolded weight, and --color-text-secondary (which is concurrent with dotcom's org/repo H1):

![""](https://user-images.githubusercontent.com/40274682/110014523-bd428c00-7cd7-11eb-992c-0f8181d3d8e1.png)

They are both the same font size though the screenshot is misleading. 

I'm unable to locate an example of the breadcrumb using the body text in dotcom to verify what's in use. 

Should we look at filing an issue to update primer or look at updating Figma or a combo of both?

**Comment by ashygee** [comment]
Thanks for submitting this @ichelsea, I'll look into this and make a note within our pattern backlog to investigate as well.
