### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by loeffel-io** [primer/figma#9]
Possible that the progress bar is missing in primer web?

**Comment by lukasoppermann** [comment]
Yes, the component is definitely missing. I'll see if we can get it into figma.

**Comment by lukasoppermann** [comment]
Hey @loeffel-io,

sorry for the long wait, but now it is available: https://www.figma.com/file/GCvY3Qv8czRgZgvl1dG6lp/Primer-Web?node-id=16163%3A61220
